project:
  type: website

website:
  title: "Weiynnâ€™s Research Blog"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Blog
        href: posts/index.qmd

format:
  html:
    theme: default
    css: styles.css

metadata-files: [bibtex.yml]